### ISSUE TITLE
Window buttons

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/endlish-oesque#9]
https://github.com/endlessm/eos-theme/blob/862beae4382996705d36e4c17598b9fb57d70692/settings/com.endlessm.settings.gschema.override.in#L26-L27

**Comment by castrojo** [comment]
Shouldn't we just grab that entire file to start with?

**Comment by cassidyjames** [comment]
@castrojo I did basically that in 6e69836c1c79c083d019cf33e1743179a7d08844, but some of the settings were pretty outdated, so I only grabbed what I think is relevant.
